### ISSUE TITLE
Atom: не работает поиск по целому слову для os-файлов

### ISSUE THREAD

**Issue by artbear** [1c-syntax/1c-syntax#141]
Если выполняю поиск в os-файле через Ctrl-F или Ctrl-Shift-F по целому слову, то ничего не находится.
Поиск без учета целого слова работает верно.
В обычных файлах, например, мд-файлах, поиск по целому слову работает.

**Comment by nixel2007** [comment]
Есть мнение, что это опять из-за `\w` в регулярках (поиск по латинице-то работает) и это надо править в самом Атоме.

**Comment by artbear** [comment]
Ага, в мд-файлах также русские имена не ищутся :(
Куда issue создавать?

**Comment by nixel2007** [comment]
Куда-то вот сюда.
https://github.com/atom/find-and-replace

Но судя по >180 ишузам (пффф, кто бы сомневался с их-то скоростью), там это уже есть. по крайней мере народ уже предлагает онигуруму. Не в первый раз, кстати. Немцы тоже усиленно страдают.

**Comment by bambr1975** [comment]
https://github.com/atom/find-and-replace/blob/66f09c532bb4f7b941282b99d4daf85a08d2288c/lib/find-options.coffee#L60

**Comment by nixel2007** [comment]
Кто бы, блин, сомневался...

**Comment by theshadowco** [comment]
кмк, стоит закрыть
