### ISSUE TITLE
Цветовая схема

### ISSUE THREAD

**Issue by EvilBeaver** [1c-syntax/1c-syntax#21]
Нужна классическая цветовая схема, как в конфигураторе, плюс, как в Eclipse. Однозначно будут просить.

**Comment by nixel2007** [comment]
Согласен.

**Comment by pumbaEO** [comment]
не надо делать вырвиглазную тему, плиз, лучше учить хорошему, чем плохому.

2015-12-09 12:02 GMT+03:00 Nikita Gryzlov <notifications@github.com>:

> Согласен.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/1c-syntax/issues/21#issuecomment-163155132>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by artbear** [comment]
Ага, я также согласен, что классическая схема корявая :(
Если желающие будут, пусть сами и делают :)

**Comment by nixel2007** [comment]
> Если желающие будут, пусть сами и делают :)

ШИКАРНО :D 

Предлагаю дождаться первого запроса.

**Comment by nixel2007** [comment]
@CryptedSky опубликуешь? Я даже для тебя добавил отдельные токены для скобок.

**Comment by theshadowco** [comment]
Предлагаю закрывать, за 6 лет никто не пришел.
