### ISSUE TITLE
 VSC Парная подсветка кавычек

### ISSUE THREAD

**Issue by ruimage** [1c-syntax/1c-syntax#249]
Функционал: VSC Парная подсветка кавычек

Как Программист
Я хочу иметь подсветку парной кавычки в VSC 
Чтобы При работе с кодом и запросами содержащим вложенные кавычки облегчить редактирование парных кавычек 

Контекст: 
    Дано установлен модуль Language 1C
    И  тип содержимого файла установлен в BSL

Сценарий: Подсветка закрвающей кавычки 

	Когда Я устанавливаю курсор на позицию открывающей кавычки	
	Тогда Закрывающая кавычка выделяется заливкой текста в соответствии с уровнем   вложенности кавычек

Сценарий: Подсветка открывающей кавычки 

	Когда Я устанавливаю курсор на позицию закрывающей кавычки	
	Тогда Открывающая кавычка выделяется заливкой текста в соответствии с уровнем вложенности кавычек

**Comment by nixel2007** [comment]
@bambr1975 насколько я понимаю, на уровне конфига такое нельзя сделать, надо доп провайдер мутить, да?

**Comment by nixel2007** [comment]
хотя нашел вот такое в конфиге, надо попробовать:
```json
	"surroundingPairs": [
		["<", ">"],
		["'", "'"],
		["\"", "\""]
```

только проверить, как экранирование кавычек будет работать

**Comment by ruimage** [comment]
У меня не взлетело. Либо я что-то не правильно делаю.
