### ISSUE TITLE
[VSCode] Фича генерации markdown-текста описания методов модуля по коду модуля

### ISSUE THREAD

**Issue by artbear** [1c-syntax/1c-syntax#288]
@nixel2007 @bambr1975 Может быть, сделаете небольшую спец.функцию генерации маркдаун-текста в плагине для VSC, аналогично коду, приведенному Никитой в https://gitter.im/EvilBeaver/oscript-library?at=591774f783cb5db0732a9e16 ?

>@nixel2007 : я вмешался в одну из команд плагина для 1с

         let methods = global.db.find({ filename: "d:/git/nixel2007/gitrunner/src/Классы/ГитРепозиторий.os" }); 
        let md = ""; 
        for (let method of methods) { 
            if (!method._method.IsExport) { 
                continue; 
            } 
            md += "### " + method.name + "\n"; 
            md += `\`\`\`bsl\n`; 
            md += method.description + "\n"; 
            md += `\`\`\``; 
            md += "\n"; 
        }

>потом просто скопипастил накопившиеся в md
это старая версия в черновиках лежит. сейчас формат чуть отличается (я его потом напильником доводил)

**Comment by bambr1975** [comment]
Просто команда, которая формирует md-файл для открытого файла с  диалогом, куда сохранять? Или кнопка в СП, которая всю справку по библиотеке в md выводит? Или и то и другое и можно без хлеба?

**Comment by nixel2007** [comment]
Для начала можно вообще открыть новое окно эдитора с полученным текстом. А оттуда автор уже может спокойно коаипастить, куда ему надо.

**Comment by nixel2007** [comment]
Сделано в 1.13.0
