### ISSUE TITLE
[VSCode] Более умная поддержка сворачивания участков кода

### ISSUE THREAD

**Issue by artbear** [1c-syntax/1c-syntax#291]
Пустые функции/процедуры не сворачиваются.
```
Процедура ПередОкончаниемСценария() Экспорт
	
КонецПроцедуры

Функция Метод1() Экспорт
	
КонецФункции
```
/cc @nixel2007 @bambr1975

**Comment by artbear** [comment]
Проверено на свежайших версии плагина и VSC (обновлено сегодня)

**Comment by nixel2007** [comment]
Артур, не вешай метки, пожалуйста.

**Comment by nixel2007** [comment]
Folding Provider API - https://code.visualstudio.com/docs/extensionAPI/vscode-api#FoldingRangeProvider

**Comment by nixel2007** [comment]
Исправлено в 1.14.0
