### ISSUE TITLE
[VSCode] Справка 1С выводится для *.os

### ISSUE THREAD

**Issue by 1cgh** [1c-syntax/1c-syntax#292]
При редактировании файлов *.os срабатывает автодополнение и СП по методам/объектам 1С, которые не реализованы в OScript. Например, ПрочитатьJSON. Хотя, насколько мне известно, *.os связаны только с оскриптом и не связаны с платформой 1С (т.е. платформа 1С пока не генерит файлы *.os, а только *.bsl).
Хотелось бы при редактировании *.os иметь справку и автодополнение, соответствующие контексту (только то, что реализовано в OScript).

**Comment by bambr1975** [comment]
Не воспроизводится.

**Comment by bambr1975** [comment]
![default](https://user-images.githubusercontent.com/9781644/46259545-843cd680-c4e3-11e8-9921-3da8a358f3d9.gif)

**Comment by 1cgh** [comment]
![17 48 37](https://user-images.githubusercontent.com/24507052/47369253-f4f29f80-d6eb-11e8-8239-e3e1f944280b.png)

**Comment by nixel2007** [comment]
ЗаписатьJSON появилась в движке

**Comment by 1cgh** [comment]
Ага. Потыкал, уже не актуально, всё работает правильно сейчас.
