### ISSUE TITLE
Получил уведомление, что расширение скоро не сможет работать, так как использует vscode.previewHtml

### ISSUE THREAD

**Issue by Bezeus** [1c-syntax/1c-syntax#308]
Получил уведомление: 
"Extension 'xDrivenDevelopment.language-1c-bsl' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API."

**Comment by alkoleft** [comment]
Пришло время и расширение перестало стабильно работать на версии 1.33

1. При редактировании (нажатии таб) возникает ошибка command 'language-1c-bsl.expandAbbreviation' not found
2. При выполнении команды "create comment for current mathod" аналогичная ошибка

**Comment by bambr1975** [comment]
Прошу прощения, из-за занятости несколько месяцев не могу добраться. Постараюсь на этой неделе разобраться.

**Comment by JAGUAR-90210** [comment]
UP. не работает синтаксис помощник syntax-helper с версии 1.33
