### ISSUE TITLE
Лишний символ в начале строкового литерала

### ISSUE THREAD

**Issue by froloid** [1c-syntax/1c-syntax#315]
Некоторые строковые литералы (большинство) получают некий "?" в начале строки. Причём при одном и том же коде может выходить различный результат в одном скрипте.

![image](https://user-images.githubusercontent.com/11738297/65658614-1ca36380-e031-11e9-98ca-37b0739c3256.png)

Попробовал скрипт на python - там зачастую добавляет пробел (или неотображаемый символ).

Не могу понять, что у меня может быть не так настроено?

'opm update -a ' естественно делал. Похоже здесь вообще не в os дело, но куда копать не пойму. VSC тоже актуальный.

**Comment by nixel2007** [comment]
Добрый день. Кодировка файла какая?

**Comment by froloid** [comment]
С запозданием приветствую!

UTF-8

**Comment by froloid** [comment]
Причём проблема наблюдается и со строками без кириллических символов.

**Comment by nixel2007** [comment]
Без bom, правильно понимаю?

Версия оскрипта? 

Таску запускаете вшитую в плагин или у вас собственный tasks.json?

**Comment by froloid** [comment]
С кодировкой чуть в тупик не поставили - в VSC не уточняется. Посмотрел в другом редакторе - С BOM.

Версия os  - 1.1.1.44

Таск на память если - то не трогал. А вот как он появился - уже не помню. Сейчас он выглядит вот так:
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558 
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "process",
            "id": "process,oscript,${file},",
            "problemMatcher": [
                "$OneScript Linter"
            ]
        }
    ]
}`

**Comment by nixel2007** [comment]
1. Попробуйте удалить bom
2. Попробуйте удалить tasks.json, и запустить встроенный в редактор таск oscript: run

**Comment by froloid** [comment]
Похоже что-то непосредственно в движке: и с BOM и без при запуске из командной строки (соответственно task не используется), результат одинаков - в первой строке вопрос.

**Comment by froloid** [comment]
[BC_merge_com.txt](https://github.com/1c-syntax/1c-syntax/files/3656460/BC_merge_com.txt)

Если есть возможность - попробуйте у себя (расширение поменял, так как иначе файл не отправить).

**Comment by nixel2007** [comment]
@EvilBeaver можно тебя попросить посмотреть?

**Comment by 240596448** [comment]
> [BC_merge_com.txt](https://github.com/1c-syntax/1c-syntax/files/3656460/BC_merge_com.txt)
> 
> Если есть возможность - попробуйте у себя (расширение поменял, так как иначе файл не отправить).

![image](https://user-images.githubusercontent.com/35220983/88324744-caa09c80-cd2c-11ea-8552-8746fe4a8c1b.png)

Дело не в BOM, без них тоже самое.
Перед символом я (я - D1 8F) стояла загадочная последовательность символов.
Диагностируется лишним нажатием backspace)
