### ISSUE TITLE
Обновить readme

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/1c-syntax#318]
Обновить файл Readme

- [x]  поправить как таковой
- [x]  информация о конфигурационном файле bslls
- [x]  офлайн установка (без интернетов)
 - использование флага  bsl ls use external jar
 - куда распаковать zip, дабы все было хорошо

**Comment by theshadowco** [comment]
Использование конфигурационного файла https://github.com/1c-syntax/vsc-language-1c-bsl/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-BSL-Language-Server

**Comment by nixel2007** [comment]
Схему бы в пример

**Comment by theshadowco** [comment]
готово https://github.com/1c-syntax/vsc-language-1c-bsl/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0

**Comment by nixel2007** [comment]
Вариант 2 не совсем верен, распаковка идёт не туда. :)
Вариант 1 - нужно ещё включить галку use external jar. Но я не вижу у тебя её на скриншоте, ты их с релиза делал?

**Comment by theshadowco** [comment]
Вариант 1 - с установленной версии... наверное нада обновиться с dev

**Comment by theshadowco** [comment]
Вариант 2 - наверное связана, ибо у меня счас там усе лежит

**Comment by nixel2007** [comment]
> Вариант 1 - с установленной версии... наверное нада обновиться с dev

не с дев, а с фича бранча или собранного vsix.

**Comment by nixel2007** [comment]
> Вариант 2 - наверное связана, ибо у меня счас там усе лежит

у тебя сейчас там лежит жарник. а zip распаковывается в globalStorage VSCode, который лежит в другом месте.

**Comment by theshadowco** [comment]
![image](https://user-images.githubusercontent.com/9591731/72718949-fb3e2880-3b87-11ea-85fd-645b6cf53043.png)

**Comment by theshadowco** [comment]
поправил
