### ISSUE TITLE
VSC: A request has failed при любом действии

### ISSUE THREAD

**Issue by aleksandr-ermakov** [1c-syntax/1c-syntax#322]
1. Создаём новый файл, не сохраняем.
2. Включаем синтаксис = BSL
3. Делаем что угодно в файле, пишем что угодно, да просто тыкаем курсором - на каждое действие вываливается гора ошибок в журнале.

VSC: 1.42.1
Java: build 1.8.0_231-b11
[Output.txt](https://github.com/1c-syntax/1c-syntax/files/4239425/Output.txt)

**Comment by nixel2007** [comment]
Проблема известна, связана с обработкой несохраненных файлов. Переключите в настройках версию bsl ls на пре-релиз или дождитесь релиза bsl ls.
