### ISSUE TITLE
Программные модули не должны иметь закомментированных фрагментов кода

### ISSUE THREAD

**Issue by qazard** [1c-syntax/1c-syntax#323]
"закомМентированных" - опечатка в слове.

В VS code выделяет как ошибочный комментарий. Так и должно быть ?

![image](https://user-images.githubusercontent.com/34959569/75659158-9394f600-5c7a-11ea-956e-c1aa76956fea.png)

**Comment by EvilBeaver** [comment]
Поясните суть вопроса, пожалуйста:

* в тексте сообщения VSCode опечатка и нужно писать с одной М?
* в коде вашей программы написано "комментированных" и VSCode это выделяет, как ошибку?

Что из этого?

**Comment by qazard** [comment]
Добрый день, удалите пожалуйста мой пост. Спасибо

Ошибок нет

**Comment by EvilBeaver** [comment]
нажмите кнопку "Close issue" самостоятельно
