### ISSUE TITLE
Использование в javascript

### ISSUE THREAD

**Issue by woodholly** [1c-syntax/1c-syntax#326]
Можно ли как-то использовать ваши наработки для простого подсвечивания кода на javascript?
Грубо: есть строка с 1с кодом, а на выходе строка с подсветкой ?
Аналогочный вопрос для PHP.

**Comment by EvilBeaver** [comment]
Поясните use-case подробнее, пожалуйста. Подсвечивать где? Строка с кодом javascript где есть? В коде 1С? или что?
Не хватает контекста

**Comment by woodholly** [comment]
я имею ввиду есть ли javascript обёртка для ваших правил, помощью которых можно подсвечивать 1с код на javascript ?

**Comment by nixel2007** [comment]
Есть вот такой пакет:
https://www.npmjs.com/package/vscode-textmate

Не знаю, насколько он вам подойдёт. Надо понимать, что TextMate-бандлы - это про токенизацию текста - раскладывание его на лексемы. А раскрашивание лексем - это несколько другая задача.

Если вам нужна обычная подсветка 1с-ного кода из javascript, то возьмите, например, highlight.js. Там токенизатор потупее и не поддерживает новых фич языка, но для простых случаев вполне подойдёт.

В этой же организации ещё есть форк редактора Ace с частично реализованной подсветкой для 1с. Если оно все ещё собирается, но тоже может подойти. Плюс можно таки сесть и написать свой токенайзер для CodeMirror. Там формат грамматики несколько отличается от TextMate, но основную логику перенести можно.

**Comment by nixel2007** [comment]
Вспомнил, ещё есть вот такой проект - редактор кода 1с на базе monaco

https://github.com/salexdv/bsl_console

**Comment by EvilBeaver** [comment]
По-моему, на базе Монако самый продвинутый и готовый

**Comment by woodholly** [comment]
Спасибо огромное!

**Comment by nixel2007** [comment]
Рады помочь!
