### ISSUE TITLE
Как указать эту грамматику в сообщении github?

### ISSUE THREAD

**Issue by tormozit** [1c-syntax/1c-syntax#330]
На этом сайте в форме ввода сообщения выполнил команду "insert code". Какой указать код грамматики, чтобы к тегу "code" применилась она?

**Comment by nixel2007** [comment]
bsl

**Comment by tormozit** [comment]
Это я попробовал первым делом. Но получил неожиданный результат. Потому начал перебирать остальное и искать его.

![изображение](https://user-images.githubusercontent.com/11896251/130511436-8a572465-e2e4-4741-aa53-20f410c4ea36.png)


![изображение](https://user-images.githubusercontent.com/11896251/130511437-f574b3b2-5cb0-4104-823e-906bd96bbcac.png)

**Comment by nixel2007** [comment]
А что в нем неожиданного?

**Comment by tormozit** [comment]
В оригинале 
![изображение](https://user-images.githubusercontent.com/11896251/130525120-9f73d30e-1979-4616-ba17-4700852c3902.png)

**Comment by EvilBeaver** [comment]
Речь о конкретных цветах? В них проблема?

**Comment by asosnoviy** [comment]
```bsl

**Comment by tormozit** [comment]
Думал в таком коротком тексте будет очевидно. Зачем "ВК" окрашивается особым цветом?

**Comment by nixel2007** [comment]
ВК окрашивается особым цветом, т.к. это присваивание. Выделение идентификатора в операции присваивания - частая и удобная практика из многих IDE.

Но отмечу, что проект 1c-syntax не управляет _цветами_ текста. Он задает правила токенизации и классификации токенов. За конкретные цвета отвечает цветовая тема.

P.S. Цветовая схема конфигуратора, имхо, ужасна.

**Comment by tormozit** [comment]
> ВК окрашивается особым цветом, т.к. это присваивание. Выделение идентификатора в операции присваивания - частая и удобная практика из многих IDE.

Ясно. Присмотрелся в VSCode. Действительно и там цвета отличаются, но там значительно меньше акцент на присваивании. Как то можно его уменьшить (изменить цветовую схему) для репозитория или в каких то настройках пользователя github ?

> Цветовая схема конфигуратора, имхо, ужасна
Это дело вкуса и его пластичности (привыкания).

**Comment by nixel2007** [comment]
> Как то можно его уменьшить (изменить цветовую схему) для репозитория или в каких то настройках пользователя github ?

В тёмной теме код выглядит по-другому. Остальное - только через user styles вероятно. Может какие расширения для бразуера есть готовые на этот счёт. Я для гх просто использую тёмную тему.
