### ISSUE TITLE
В автодополнение попадают символы из комментариев

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/1c-syntax#49]
Тоже пожелание от коллеги.
Если есть закомментированный кусок кода:

```
// Процедура ТестоваяПроцедура()
// А = 0;
// // Даже просто с обычными комментариями
// КонецПроцедуры
```

То в автокомплит попадают все токены из комментов: и `ТестоваяПроцедура`, и `Даже`, и `обычными`, все подряд. (подтверждено на ST)

Не знаю, можно ли это как-то настроить, но как пожелание зафиксирую.

**Comment by EvilBeaver** [comment]
Я не понял, это фича, что попадают символы из комментариев или бага? Мне эта фича сильно нравится. Давайте ее не будем убирать (если такие планы есть)?

**Comment by nixel2007** [comment]
Коллега считает, что это баг :)

Надо проверить, как работает автокомлит в атоме, в питоне, например (где он "умный", а не посимвольный)

**Comment by EvilBeaver** [comment]
Коллега просто не прочувствовал прелесть, когда у тебя автокомплит понимает даже то, что написано в строковых литералах и каментах.

**Comment by nixel2007** [comment]
Про строковые литералы соглашусь, мне в ST было очень удобно заниматься переводом codecombat.com. А вот от коментов какая польза?

**Comment by theshadowco** [comment]
актуально?

**Comment by nixel2007** [comment]
вроде сошлись на том, что won't fix
